### ISSUE TITLE
Needs fix by Django 4.x

### ISSUE THREAD

**Issue by tulgaab** [andreynovikov/django-daterangefilter#11]
`Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/django/apps/config.py", line 126, in create
    mod = import_module(mod_path)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/khureltulga/Documents/GitHub/redrockweb/.env/lib/python3.8/site-packages/daterangefilter/apps.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'`

**Comment by ZephSibley** [comment]
@andreynovikov @cansarigol 
The only change required:
_daterangefilter.apps line 2_
from:
`from django.utils.translation import ugettext_lazy as _`
to:
`from django.utils.translation import gettext_lazy as _`

**Comment by vb64** [comment]
You can try this one: https://github.com/vb64/django.admin.filters

**Comment by andreynovikov** [comment]
Fixed
